### ISSUE TITLE
.start(); and .play(); both broken.

### ISSUE THREAD

**Issue by harshonyou** [mandreasen/CSGOCoordinator#3]
Both the commands are giving me error; seems like its been a while since any update. 
"this._connection.send(Buffer.concat([header.toBuffer(), body])); TypeError: Cannot read property 'send' of undefined
    at CMClient._send (C:\Users\Kaneki Sasaki\Desktop\NodeT\Report\node_modules\steam-client\lib\cm_client.js:241:19)
    at CMClient.send (C:\Users\Kaneki Sasaki\Desktop\NodeT\Report\node_modules\steam-client\lib\cm_client.js:271:7)
    at SteamGameCoordinator._send (C:\Users\Kaneki Sasaki\Desktop\NodeT\Report\node_modules\steam\lib\handlers\game_coordinator\index.js:49:16)
    at SteamGameCoordinator.send (C:\Users\Kaneki Sasaki\Desktop\NodeT\Report\node_modules\steam\lib\handlers\game_coordinator\index.js:67:8)
    at Timeout._onTimeout (C:\Users\Kaneki Sasaki\Desktop\NodeT\Report\node_modules\csgocoordinator\index.js:116:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)"

**Comment by mandreasen** [comment]
Hi.

Can you post a snippet of your code where you initialize the modules etc. and just to be sure. You are using node-steam not node-steam-user.

_I don't have time to retest the code today, but I'll take a look on it if I don't find the error in your code snippet._

**Comment by harshonyou** [comment]
Hey, first of all thanks for that quick responce.
I ran your [example code](https://github.com/mandreasen/CSGOCoordinator/blob/master/example.js) and .start(); did not send any error, beside the fact commands wasn't able to send. 
Here's the output.
![image](https://user-images.githubusercontent.com/22548610/80858120-da03d280-8c74-11ea-8da6-87605bfb9645.png)

Maybe my code is wrong/outdated; I wrote it in 2018 so maybe something's off, anyway here's the code: 
```js
var numberofaccountlist = 1;
const SteamUser = require('steam-user');
var Steam = require('steam-client');
var _steam = require('steam')
const SteamTotp = require('steam-totp');
const CSGOCoordinator = require('csgocoordinator');
var readlineSync = require("readline-sync")
const fs = require('fs')

const ClientHello = 4006;
const ClientWelcome = 4004;

function ProcessCommend(targetID,username,password,sharedSecret) {
    var steamClient = new Steam.CMClient();
    var steamUser = new SteamUser(steamClient)
    var steamGC = new _steam.SteamGameCoordinator(steamClient, 730)
    var steamCSGO = new CSGOCoordinator(steamUser,steamGC)

    if (sharedSecret) {
        steamUser.logOn({
            accountName: username,
            password: password,
            twoFactorCode: SteamTotp.generateAuthCode(sharedSecret)
        });
    } else {
        steamUser.logOn({
            accountName: username,
            password: password,
        });
    }

    steamUser.once('loggedOn', function(details) {
        steamUser.setPersona(SteamUser.EPersonaState.Online);
        steamUser.gamesPlayed([730]);
        //steamCSGO.start();
        console.log(`${username} Connected to User!`);
        steamCSGO.once('ready',()=>{
            try{
                console.log(`${username} Account Ready. Sending Praise!`)
                steamCSGO.player.commend(steamCSGO.SteamID2AccountID(targetID), true, true, true)
            } catch (ex) {
                console.error(ex)
            }
        })
    });
    

    steamCSGO.once('commendResponse',(response) => {
        if (response.response_result === 1){
            console.log("SENT!");
        } else {
            console.log("ERROR!")
        }
    })

}
```

**Comment by mandreasen** [comment]
Like you discover yourself, the problem is not with CSGOCoordinator.

The problem is that you are using the node-steam-user SteamUser object when CSGOCoordinator requires a node-steam SteamClient object. There for CSGOCoordinator can't fint the objects it's trying to use, which results in error.

You can look at the example in the README.md file.
https://github.com/mandreasen/CSGOCoordinator#initializing
