### ISSUE TITLE
GC is not ready

### ISSUE THREAD

**Issue by samyycX** [mandreasen/CSGOCoordinator#4]
I got a "GC is not ready" error when i use `csgo.player.requestProfile(AccountID)`. What should I do?

**Comment by mandreasen** [comment]
Make sure that you are running CSGO.

**Comment by samyycX** [comment]
> Make sure that you are running CSGO.

im running csgo.

**Comment by mandreasen** [comment]
Do you use [play()](https://github.com/mandreasen/CSGOCoordinator#csgoplaygamesplayed)? If not, remember to use [start()](https://github.com/mandreasen/CSGOCoordinator#csgostart) after you have started CSGO from somewhere else within your code. That will start the GC ClientHello and when the GC is ready, the event [ready](https://github.com/mandreasen/CSGOCoordinator#ready) will be triggeret.

**Comment by samyycX** [comment]
> Do you use [play()](https://github.com/mandreasen/CSGOCoordinator#csgoplaygamesplayed)? If not, remember to use [start()](https://github.com/mandreasen/CSGOCoordinator#csgostart) after you have started CSGO from somewhere else within your code. That will start the GC ClientHello and when the GC is ready, the event [ready](https://github.com/mandreasen/CSGOCoordinator#ready) will be triggeret.

ok, so i need to listen to "ready" event, and listen to "playerProfile" event in the "ready" event listener?

**Comment by mandreasen** [comment]
No.

You can use the ready event to know when the GC is ready and when the GC is ready then you can send other commands. So when the GC is ready, you can for eksample send the playerProfile command.

Remember to read the [README.md](https://github.com/mandreasen/CSGOCoordinator/blob/master/README.md) file and that you need to use node-steam not node-csgo else you will have to fake objects.

**Comment by samyycX** [comment]
> No.
> 
> You can use the ready event to know when the GC is ready and when the GC is ready then you can send other commands. So when the GC is ready, you can for eksample send the playerProfile command.
> 
> Remember to read the [README.md](https://github.com/mandreasen/CSGOCoordinator/blob/master/README.md) file and that you need to use node-steam not node-csgo else you will have to fake objects.


```
var Steam = require('steam'),
    steamClient = new Steam.SteamClient(),
    steamUser = new Steam.SteamUser(steamClient),
    csgo = require('csgocoordinator');
	var steamGC = new Steam.SteamGameCoordinator(steamClient, 730);
	var CSGO = new csgo(steamUser, steamGC);
	
	steamClient.connect();
	steamClient.on('connected',function() {
		steamUser.logOn({
			account_name: '',
			password: ''
		});
	});
	
	steamClient.on('logOnResponse', function(response) {
		if (response.eresult == Steam.EResult.OK) {
			console.log("Steam logged in."); //This line successfully outputs
			CSGO.play();
			CSGO.start();
		}
	});
	
	CSGO.on('ready', (ready) => {
		if (ready) {
			console.log("CSGO Coordinator is ready."); //This line cannot be output
			CSGO.player.requestProfile(1084512653);
		}
	});
	
	CSGO.on('playerProfile',(profile) => {
		console.log('123');
	});
	
	
	
```

ok, this is my code. I dont know why, the ready event is never trigger. same for example.js.

**Comment by mandreasen** [comment]
Sorry dude, but I don't have time for that at the moment and I have just run my test script which steel work fine, so there should not be any issues with the module.

Try using the debug tool:
`var CSGO = new csgo(steamUser, steamGC, true);`
`CSGO.on('debug', function(message) {
	console.log("DEBUG:", message);
});`

You don't need to use CSGO.start() when you use CSGO.play(). CSGO.play() automatically run start();

You can also try and run the example script with your account. To see if that make any difference in your problem.

**Comment by samyycX** [comment]
> Sorry dude, but I don't have time for that at the moment and I have just run my test script which steel work fine, so there should not be any issues with the module.
> 
> Try using the debug tool:
> `var CSGO = new csgo(steamUser, steamGC, true);`
> `CSGO.on('debug', function(message) { console.log("DEBUG:", message); });`
> 
> You don't need to use CSGO.start() when you use CSGO.play(). CSGO.play() automatically run start();
> 
> You can also try and run the example script with your account. To see if that make any difference in your problem.

really thanks, i guess maybe my event listener go something wrong, because the debug event listener doesn't work too, sames as example.js. but thanks for help

**Comment by samyycX** [comment]
> Sorry dude, but I don't have time for that at the moment and I have just run my test script which steel work fine, so there should not be any issues with the module.
> 
> Try using the debug tool:
> `var CSGO = new csgo(steamUser, steamGC, true);`
> `CSGO.on('debug', function(message) { console.log("DEBUG:", message); });`
> 
> You don't need to use CSGO.start() when you use CSGO.play(). CSGO.play() automatically run start();
> 
> You can also try and run the example script with your account. To see if that make any difference in your problem.

hey, what's your node version?

**Comment by samyycX** [comment]
> Sorry dude, but I don't have time for that at the moment and I have just run my test script which steel work fine, so there should not be any issues with the module.
> 
> Try using the debug tool:
> `var CSGO = new csgo(steamUser, steamGC, true);`
> `CSGO.on('debug', function(message) { console.log("DEBUG:", message); });`
> 
> You don't need to use CSGO.start() when you use CSGO.play(). CSGO.play() automatically run start();
> 
> You can also try and run the example script with your account. To see if that make any difference in your problem.

i think i know the problem，my steamGameCoordinator never accept the clienthello

**Comment by samyycX** [comment]
> Sorry dude, but I don't have time for that at the moment and I have just run my test script which steel work fine, so there should not be any issues with the module.
> 
> Try using the debug tool:
> `var CSGO = new csgo(steamUser, steamGC, true);`
> `CSGO.on('debug', function(message) { console.log("DEBUG:", message); });`
> 
> You don't need to use CSGO.start() when you use CSGO.play(). CSGO.play() automatically run start();
> 
> You can also try and run the example script with your account. To see if that make any difference in your problem.

ok, i solved this problem. I made a stupid mistake, i forgot to own csgo in my steam account. what a stupid mistake
